### ISSUE TITLE
integration-gradle-inspector fails with Gradle 6.8.x

### ISSUE THREAD

**Issue by lambliesdown** [blackducksoftware/integration-gradle-inspector#10]
The following calls will fail with gradle 6.8
              renderer.setOutputFile(outputFile)
                renderer.startProject(project)
due to this https://github.com/gradle/gradle/commit/4fded987beada89c79d909f1f69b602bd49184cc#diff-c056961086968375d619e9693cd4dc8b8d487cddd43522272ccb55dd945a9304L56 change in gradle.

Error is
* What went wrong:
Execution failed for task ':dependencies'.
> No signature of method: org.gradle.api.tasks.diagnostics.internal.dependencies.AsciiDependencyReportRenderer.startProject() is applicable for argument types: (org.gradle.api.internal.project.DefaultProject_Decorated) values: [root project 'svc40-framework']
  Possible solutions: startProject(org.gradle.api.tasks.diagnostics.internal.ProjectDetails), startProject(org.gradle.api.tasks.diagnostics.internal.ProjectDetails)

**Comment by croitorgheorghita** [comment]
I have the same problem. The Gradle version is now 7.1.
Does anyone know if any change will be made in the near future?

**Comment by lambliesdown** [comment]
Works fine with the 7.x versions of synopsis-detect.jar

**Comment by derlih** [comment]
NOTE: If you download the "latest" version from https://detect.synopsys.com/detect.sh actually it's not the latest one.
The landing page https://detect.synopsys.com tells:

> Please use this URL + /detectN.sh or /detectN.ps1 where N is the Detect major version number. Use /detect.sh or /detect.ps1 for Detect version 6. 

To fix it for myself I switched to https://detect.synopsys.com/detect7.sh
