### ISSUE TITLE
Parsing Dependency Report Output is a VERY Bad Idea

### ISSUE THREAD

**Issue by EarthCitizen** [blackducksoftware/integration-gradle-inspector#7]
My understanding of Hub Detect is that it executes Gradle dependency reports and consumes the output. This is a very, **_very_** bad idea. There is not a contract for the report output. That I have seen, Gradle is not promising that this output follow a contract as a REST API would do. This report output is not indented to be programmatically consumed.

Additionally, this project is using a Gradle internal class to execute the report (`org.gradle.api.tasks.diagnostics.internal.dependencies.AsciiDependencyReportRenderer`), which is another very bad idea since "internal" classes should not be used.

The project hub-gradle-plugin correctly gets the dependencies programmatically, as should be done. 

This project needs to change it's dependency collection method to programmatic instead of executing the Gradle ASCII dependency report. We are seeing in our scans that Hub Detect is reporting incorrect dependency versions exactly because of trying to parse the dependency reports generated by integration-gradle-inspector.

Please don't try to improve or fix the parsing of the Gradle ASCII dependency report. That method will never be stable. Please make this project get the dependencies programmatically.

**Comment by shafr** [comment]
& Speaking of AsciiDependencyReportRenderer I'm getting error that fails scan:
```
No signature of method: org.gradle.api.tasks.diagnostics.internal.dependencies.AsciiDependencyReportRenderer.startProject() is applicable for argument types: (org.gradle.api.internal.project.DefaultProject_Decorated) values: [root project '<PROJECT>']
  Possible solutions: startProject(org.gradle.api.tasks.diagnostics.internal.ProjectDetails), startProject(org.gradle.api.tasks.diagnostics.internal.ProjectDetails)
```

**Comment by shafr** [comment]
This commit breaks everything:
https://github.com/gradle/gradle/commit/4fded987beada89c79d909f1f69b602bd49184cc

**Comment by shafr** [comment]
@psantos1113 any chance that this would be fixed ? Or any instructions how to test it locally ?

**Comment by psantos1113** [comment]
Hi @shafr this project is no longer used or maintained any longer.  The functionality provided here is obsolete at this time.
